"""CleanSheet Pro — PDF Quality Report Generation.

Generates a professional one-page PDF summary with:
- Dataset overview (rows, columns, size)
- Data quality score (0-100)
- Issues found (missing, duplicates, outliers)
- Cleaning operations applied
- Before/after comparison
"""

import io
from datetime import datetime

from fpdf import FPDF
import streamlit as st
import pandas as pd

from src.profiler import profile_dataset
from components_pro.quality_score import compute_score


def generate_pdf_report(
    df_before: pd.DataFrame | None,
    df_after: pd.DataFrame,
    cleaning_log: list[str] | None = None,
    filename: str = "dataset",
) -> bytes:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "CleanSheet AI — Data Quality Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    after_profile = profile_dataset(df_after)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Dataset Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"File: {filename}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Rows: {after_profile.row_count:,}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Columns: {after_profile.column_count}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Memory: {after_profile.memory_usage}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)

    score = compute_score(df_after)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, f"Data Quality Score: {score.overall}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Completeness: {score.completeness}/100 (weight 30%)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Uniqueness:     {score.uniqueness}/100 (weight 20%)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Consistency:    {score.consistency}/100 (weight 25%)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Validity:       {score.validity}/100 (weight 25%)", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)

    if after_profile.total_missing_cells > 0 or after_profile.duplicate_count > 0:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Issues Found", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        if after_profile.total_missing_cells > 0:
            pdf.cell(0, 6, f"Missing values: {after_profile.total_missing_cells:,}", new_x="LMARGIN", new_y="NEXT")
        if after_profile.duplicate_count > 0:
            pdf.cell(0, 6, f"Duplicates: {after_profile.duplicate_count:,}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    if cleaning_log:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Cleaning Actions Applied", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for entry in cleaning_log:
            pdf.cell(0, 6, f"- {entry}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by CleanSheet AI — cleansheet-ai.streamlit.app", align="C", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()


def render_pdf_report(df: pd.DataFrame) -> None:
    st.markdown("### 📄 PDF Quality Report")
    st.markdown("Generate a professional PDF summary of your dataset quality.")

    if st.button("Generate PDF Report", type="primary", use_container_width=True):
        with st.spinner("Generating PDF..."):
            pdf_bytes = generate_pdf_report(
                df_before=st.session_state.get("df_original"),
                df_after=df,
                cleaning_log=st.session_state.get("cleaning_log"),
                filename=st.session_state.get("filename", "dataset"),
            )
        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_bytes,
            file_name="cleansheet_report.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
        st.success("PDF report generated!")
