[theme]
primaryColor = "#06B6D4"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#111827"
textColor = "#F1F5F9"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false

[global]
developmentMode = false
